import json
import math
from functools import lru_cache
from pathlib import Path

import numpy as np

from src.embeddings import (
    article_content_text,
    encode_texts,
    find_e5_phrase_matches,
    user_interest_text,
)
from src.llm_extractor import article_extraction_text
from src.scoring import exact_match_score, is_direct_match, score_article_for_user


TOKEN_PREVIEW_LIMIT = 24


@lru_cache(maxsize=1)
def _load_demo_tokenizer(adapter_path):
    from transformers import AutoTokenizer

    return AutoTokenizer.from_pretrained(adapter_path, token=False)


@lru_cache(maxsize=1)
def _adapter_summary(adapter_path):
    adapter_path = Path(adapter_path)
    config_path = adapter_path / "adapter_config.json"
    weights_path = adapter_path / "adapter_model.safetensors"
    config = json.loads(config_path.read_text(encoding="utf-8"))

    parameter_count = 0
    tensor_count = 0
    try:
        from safetensors import safe_open

        with safe_open(weights_path, framework="pt") as weights:
            for key in weights.keys():
                shape = weights.get_slice(key).get_shape()
                parameter_count += math.prod(shape)
                tensor_count += 1
    except (ImportError, OSError):
        parameter_count = None
        tensor_count = None

    return {
        "base_model": config["base_model_name_or_path"],
        "method": "QLoRA (4-bit Qwen + trainable LoRA adapter)",
        "rank": config["r"],
        "alpha": config["lora_alpha"],
        "dropout": config["lora_dropout"],
        "target_modules": sorted(config["target_modules"]),
        "parameter_count": parameter_count,
        "tensor_count": tensor_count,
        "adapter_size_mb": round(weights_path.stat().st_size / 1024 / 1024, 1),
    }


def _tokenizer_stage(article, adapter_path):
    text = article_extraction_text(article)
    try:
        tokenizer = _load_demo_tokenizer(str(adapter_path))
        token_ids = tokenizer.encode(text, add_special_tokens=False)
        token_strings = tokenizer.convert_ids_to_tokens(token_ids[:TOKEN_PREVIEW_LIMIT])
        preview = []
        for token_id, token_string in zip(token_ids[:TOKEN_PREVIEW_LIMIT], token_strings):
            preview.append(
                {
                    "id": token_id,
                    "token": token_string,
                    "decoded": tokenizer.decode([token_id], skip_special_tokens=False),
                }
            )
        return {
            "status": "ready",
            "input_text": text,
            "token_count": len(token_ids),
            "vocabulary_size": len(tokenizer),
            "preview_limit": TOKEN_PREVIEW_LIMIT,
            "preview": preview,
        }
    except Exception as exc:
        return {
            "status": "unavailable",
            "input_text": text,
            "error": str(exc),
            "preview": [],
        }


def _training_progress(root):
    metrics_path = root / "output" / "entity_extraction_qwen25_3b" / "metrics.json"
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    baseline = metrics["baseline"]
    trained = metrics["trained"]
    return {
        "baseline": baseline,
        "trained": trained,
        "f1_improvement_points": round((trained["micro_f1"] - baseline["micro_f1"]) * 100, 2),
        "json_improvement_points": round(
            (trained["json_validity"] - baseline["json_validity"]) * 100,
            2,
        ),
        "note": "Measured on the fixed five-example test split. This proves learning, not production quality.",
    }


def _qwen_extraction_stage(article, extraction_records):
    record = next(
        (item for item in extraction_records if item["article_id"] == article["article_id"]),
        None,
    )
    if record:
        return {
            "status": "saved_adapter_output",
            "model": record["model"],
            "review_status": record.get("review_status", "unknown"),
            "raw_model_output": record.get("raw_model_output", ""),
            "model_labels": record.get("model_labels", record["labels"]),
            "final_labels": record["labels"],
            "relationships": record["labels"].get("relationships", []),
            "note": "This JSON was generated by Qwen plus the saved LoRA adapter, then stored for fast inspection.",
        }

    if article.get("llm_extraction"):
        return {
            "status": "saved_adapter_output",
            "model": article["llm_extraction"].get("model"),
            "review_status": article["llm_extraction"].get("review_status"),
            "final_labels": article.get("tags", {}),
            "relationships": article["llm_extraction"].get("relationships", []),
        }

    return {
        "status": "not_run_for_article",
        "model": None,
        "review_status": None,
        "raw_model_output": None,
        "model_labels": None,
        "final_labels": article.get("tags", {}),
        "relationships": [],
        "note": (
            "Demonstration limitation: this article has no saved Qwen + LoRA inference. Its "
            "prewritten mock catalogue tags keep the recommendation stage visible, but they are "
            "not a live trained result. The future prototype must run the trained adapter for "
            "every incoming article and store a versioned result for review."
        ),
    }


def _entity_stage(article):
    return {
        "matched_entities": article.get("entities", []),
        "unknown_candidates": article.get("unknown_candidates", []),
        "canonical_tags": article.get("tags", {}),
        "note": (
            "Demonstration limitation: the current prototype uses manually configured catalogue "
            "aliases, so it only recognizes known entries. After the learned entity linker is "
            "trained and validated, the prototype must replace this path with model-scored links "
            "and human review for uncertain matches."
        ),
    }


def _structured_match_stage(user, article):
    metadata_score = exact_match_score(user, article)
    required_filters = user.get("required_filters", {})
    uses_required_filters = any(required_filters.values())
    filter_source = required_filters if uses_required_filters else user.get("interests", {})
    article_filters = article.get("tags", {})
    filter_comparison = []

    for category, user_values in filter_source.items():
        if not user_values:
            continue
        article_values = article_filters.get(category, [])
        normalized_user = {str(value).strip().casefold() for value in user_values}
        normalized_article = {str(value).strip().casefold() for value in article_values}
        shared = normalized_user.intersection(normalized_article)
        filter_comparison.append(
            {
                "category": category,
                "user_values": [
                    {
                        "value": value,
                        "matched": str(value).strip().casefold() in shared,
                    }
                    for value in user_values
                ],
                "article_values": [
                    {
                        "value": value,
                        "matched": str(value).strip().casefold() in shared,
                    }
                    for value in article_values
                ],
                "matched": bool(shared),
            }
        )

    matched_categories = sum(item["matched"] for item in filter_comparison)
    return {
        "user_interest": user["query"],
        "structured_interests": user.get("interests", {}),
        "required_filters": required_filters,
        "filter_source": "required filters" if uses_required_filters else "structured interests",
        "filter_comparison": filter_comparison,
        "matched_filter_categories": matched_categories,
        "total_filter_categories": len(filter_comparison),
        "metadata_score": metadata_score,
        "direct_match": is_direct_match(user, article),
        "note": (
            "Qwen + LoRA extracted the article facts; the current catalogue step normalized "
            "known aliases before these filters were compared."
        ),
    }


def _script_label(text):
    has_arabic = any("\u0600" <= character <= "\u06ff" for character in text)
    has_latin = any("a" <= character.casefold() <= "z" for character in text)
    if has_arabic and has_latin:
        return "Mixed Arabic and Latin text"
    if has_arabic:
        return "Arabic text"
    return "English / Latin text"


def _embedding_stage(user, article, _articles):
    user_text = user_interest_text(user)
    article_text = article_content_text(article)
    article_natural_text = " ".join(
        str(article.get(field, "")) for field in ("title", "summary", "body")
    )
    vectors = np.asarray(encode_texts([user_text, article_text]), dtype=np.float32)
    user_vector = vectors[0]
    article_vector = vectors[1]
    similarity = float(np.dot(user_vector, article_vector))

    concept_links = find_e5_phrase_matches(user["query"], article_natural_text)

    return {
        "model": "intfloat/multilingual-e5-base",
        "user_input": user_text,
        "article_input": article_text,
        "user_script_label": _script_label(user_text),
        "article_script_label": _script_label(article_natural_text),
        "vector_dimension": int(vectors.shape[1]),
        "user_vector_norm": round(float(np.linalg.norm(user_vector)), 5),
        "article_vector_norm": round(float(np.linalg.norm(article_vector)), 5),
        "dot_product_similarity": round(similarity, 4),
        "concept_links": concept_links,
        "translation_used": False,
        "note": (
            "E5 is a separate pretrained model. It compares the explicit user-interest "
            "statement with natural article text in a shared multilingual meaning space. "
            "It does not translate the article, call the entity catalogue, or receive exact filters."
        ),
    }


def build_pipeline_demo(root, user, article, extraction_records, articles=None):
    root = Path(root)
    adapter_path = root / "output" / "entity_extraction_qwen25_3b" / "adapter"
    score = score_article_for_user(user, article)

    return {
        "input": {
            "user": user,
            "article": article,
        },
        "tokenizer": _tokenizer_stage(article, adapter_path),
        "adapter": _adapter_summary(adapter_path),
        "training_progress": _training_progress(root),
        "qwen_extraction": _qwen_extraction_stage(article, extraction_records),
        "entity_enrichment": _entity_stage(article),
        "structured_result": _structured_match_stage(user, article),
        "embeddings": _embedding_stage(user, article, articles or [article]),
        "scoring": score,
    }
