from copy import deepcopy
from pathlib import Path

import nbformat
from nbclient import NotebookClient


ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_DIR = ROOT / "notebooks"
KERNEL_NAME = "python3"
PRESENTATION_TAG = "visible-presentation"


def markdown(source):
    return nbformat.v4.new_markdown_cell(source, metadata={"tags": [PRESENTATION_TAG]})


def code(source):
    return nbformat.v4.new_code_cell(source, metadata={"tags": [PRESENTATION_TAG]})


def execute_notebook(notebook):
    NotebookClient(
        notebook,
        timeout=300,
        kernel_name=KERNEL_NAME,
        resources={"metadata": {"path": str(ROOT)}},
    ).execute()
    return notebook


def qlora_fast_proof_cells():
    cells = [
        markdown(
            """## Presentation view: prove the QLoRA work without retraining

Use this section first in a meeting. It reads the real saved artifacts and makes the
training progress visible in under a minute. The complete model-loading, evaluation,
and training implementation remains below.

```text
reviewed examples -> Qwen tokens -> LoRA adapter -> before/after metrics -> Qwen JSON
```"""
        ),
        markdown(
            """### A. Show one reviewed training example and its Qwen tokens

The article is the input. The reviewed JSON is the correct answer used to calculate
fine-tuning loss. The tokenizer converts the article into IDs before Qwen processes it."""
        ),
        code(
            """import json
import math
import os
import sys
from pathlib import Path

from IPython.display import display

ROOT = Path.cwd().resolve()
if ROOT.name == 'notebooks':
    ROOT = ROOT.parent
if Path('D:/hf-cache').exists():
    os.environ.setdefault('HF_HOME', 'D:/hf-cache')
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from transformers import AutoTokenizer
from src.extraction_data import examples_by_split, load_extraction_examples

ADAPTER_DIR = ROOT / 'output' / 'entity_extraction_qwen25_3b' / 'adapter'
examples = load_extraction_examples(ROOT / 'data' / 'extraction_examples.jsonl')
splits = examples_by_split(examples)
example = splits['train'][0]

presentation_tokenizer = AutoTokenizer.from_pretrained(
    ADAPTER_DIR,
    local_files_only=True,
)
token_ids = presentation_tokenizer.encode(example['text'], add_special_tokens=False)
token_preview = [
    {
        'text_piece': presentation_tokenizer.decode([token_id]),
        'token_id': token_id,
    }
    for token_id in token_ids[:24]
]

display({
    'dataset_splits': {name: len(items) for name, items in splits.items()},
    'training_article': example['text'],
    'correct_reviewed_JSON': example['labels'],
    'article_token_count': len(token_ids),
    'tokenizer_vocabulary_size': len(presentation_tokenizer),
})
display(token_preview)"""
        ),
        markdown(
            """### B. Show what LoRA added and whether it learned

Qwen is the pretrained base model. These are the actual small adapter parameters trained
by the examples. The before/after numbers come from the untouched five-example test split."""
        ),
        code(
            """from safetensors import safe_open

adapter_config = json.loads(
    (ADAPTER_DIR / 'adapter_config.json').read_text(encoding='utf-8')
)
adapter_weights = ADAPTER_DIR / 'adapter_model.safetensors'
adapter_parameter_count = 0
adapter_tensor_count = 0
with safe_open(adapter_weights, framework='pt') as weights:
    for key in weights.keys():
        adapter_parameter_count += math.prod(weights.get_slice(key).get_shape())
        adapter_tensor_count += 1

metrics = json.loads(
    (ROOT / 'output' / 'entity_extraction_qwen25_3b' / 'metrics.json').read_text(
        encoding='utf-8'
    )
)

display({
    'base_model': adapter_config['base_model_name_or_path'],
    'method': 'QLoRA: frozen 4-bit Qwen + trainable LoRA adapter',
    'LoRA_rank': adapter_config['r'],
    'target_modules': sorted(adapter_config['target_modules']),
    'adapter_tensors': adapter_tensor_count,
    'adapter_parameters': adapter_parameter_count,
    'adapter_file_MB': round(adapter_weights.stat().st_size / 1024 / 1024, 1),
})
display({
    'BEFORE LoRA': metrics['baseline'],
    'AFTER LoRA': metrics['trained'],
    'meaning': 'The adapter improved entity extraction and produced valid JSON on every test example.',
})"""
        ),
        markdown(
            """### C. Show the saved Qwen + LoRA result

This output was generated by the trained adapter from an incoming Arabic article. It is
loaded from disk for a fast presentation; the full live-inference implementation remains
available in `src/llm_extractor.py`."""
        ),
        code(
            """extraction_path = ROOT / 'output' / 'extractions' / 'incoming_article_filters.jsonl'
saved_extractions = [
    json.loads(line)
    for line in extraction_path.read_text(encoding='utf-8-sig').splitlines()
    if line.strip()
]
saved_result = saved_extractions[0]

print('MODEL:', saved_result['model'])
print('REVIEW STATUS:', saved_result['review_status'])
print('\\nRAW GENERATED OUTPUT:')
print(saved_result['raw_model_output'])
print('\\nPARSED STRUCTURED FILTERS:')
display(saved_result['labels'])"""
        ),
        markdown(
            """### What to say before continuing

> The reviewed examples did not replace Qwen. They trained a small LoRA adapter attached
> to Qwen. Loss measured Qwen-plus-LoRA's mistakes, and backpropagation updated the adapter.
> The saved metrics prove improvement; the saved JSON shows the task the adapter learned.

The sections below contain the complete implementation used to produce these artifacts."""
        ),
    ]
    return cells


def enhance_qlora_notebook():
    path = NOTEBOOK_DIR / "tactical_report_entity_extraction_qlora.ipynb"
    notebook = nbformat.read(path, as_version=4)
    notebook.cells = [
        cell
        for cell in notebook.cells
        if PRESENTATION_TAG not in cell.get("metadata", {}).get("tags", [])
    ]

    proof_notebook = nbformat.v4.new_notebook(
        cells=deepcopy(qlora_fast_proof_cells()),
        metadata=deepcopy(notebook.metadata),
    )
    execute_notebook(proof_notebook)

    notebook.cells[1:1] = proof_notebook.cells
    nbformat.write(notebook, path)


def recommendation_cells():
    return [
        markdown(
            """# Tactical Report recommendation demonstration

This notebook shows the recommendation stage one visible step at a time. It uses the
saved Qwen extraction, canonical entity enrichment, the pretrained multilingual E5
embedding model, exact filter matching, and the final hybrid score.

```text
user interest + enriched article
    -> E5 inputs
    -> 768-dimensional vectors
    -> semantic similarity + exact evidence
    -> final score
    -> ranked recommendations
```

This notebook does **not** train Qwen or E5. Qwen's QLoRA training is demonstrated in
`tactical_report_entity_extraction_qlora.ipynb`."""
        ),
        markdown(
            """## 1. Load the same project components used by the prototype

Large model files remain on `D:`. The functions imported here are also called by the
browser application, so the notebook is not a separate fake demonstration."""
        ),
        code(
            """import json
import os
import sys
from pathlib import Path

import numpy as np
from IPython.display import display

ROOT = Path.cwd().resolve()
if ROOT.name == 'notebooks':
    ROOT = ROOT.parent
if Path('D:/hf-cache').exists():
    os.environ.setdefault('HF_HOME', 'D:/hf-cache')
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
DATA_DIR = ROOT / 'data'

from src.data_loader import (
    load_articles,
    load_entity_catalogue,
    load_evaluation_cases,
    load_incoming_articles,
    load_users,
)
from src.embeddings import article_metadata_text, encode_texts, user_metadata_text
from src.entity_enrichment import enrich_articles
from src.evaluation import evaluate_ranking_cases
from src.extraction_outputs import apply_extraction_outputs, load_extraction_outputs
from src.scoring import (
    find_embedding_signals,
    find_exact_matches,
    rank_articles_for_user,
    score_article_for_user,
)

print('Project root:', ROOT)"""
        ),
        markdown(
            """## 2. Load one user, one future article, and Qwen's saved extraction

The user profile is application input. The article starts as unstructured text. The saved
Qwen + LoRA output adds structured filters, while the catalogue connects known aliases
to canonical entity IDs."""
        ),
        code(
            """users = load_users(DATA_DIR)
catalogue = load_entity_catalogue(DATA_DIR)
extraction_records = load_extraction_outputs(
    ROOT / 'output' / 'extractions' / 'incoming_article_filters.jsonl'
)

incoming_articles = enrich_articles(load_incoming_articles(DATA_DIR), catalogue)
enriched_incoming = apply_extraction_outputs(incoming_articles, extraction_records)
articles = load_articles(DATA_DIR) + enriched_incoming

user = next(item for item in users if item['user_id'] == 'user_004')
article = next(item for item in articles if item['article_id'] == 'incoming_001')
qwen_record = next(
    item for item in extraction_records if item['article_id'] == article['article_id']
)

display({
    'USER': user['name'],
    'USER QUERY': user['query'],
    'ARTICLE': article['title'],
    'SUMMARY': article['summary'],
})
print('\\nQWEN + LORA STRUCTURED OUTPUT')
display(qwen_record['labels'])
print('CANONICAL ENTITY LINKS')
display(article['entities'])"""
        ),
        markdown(
            """## 3. Build the exact text sent to multilingual E5

E5 receives the user's profile as a `query:` and the article plus its structured metadata
as a `passage:`. Qwen's work is useful here because its filters become part of the article
representation as well as the exact-matching path."""
        ),
        code(
            """user_e5_text = user_metadata_text(user)
article_e5_text = article_metadata_text(article)

print('USER QUERY SENT TO E5:\\n')
print(user_e5_text)
print('\\nARTICLE PASSAGE SENT TO E5:\\n')
print(article_e5_text)"""
        ),
        markdown(
            """## 4. Convert both texts into visible embedding vectors

`multilingual-e5-base` creates one 768-dimensional normalized vector for each text.
Individual dimensions do not have simple names; meaning is distributed across the
complete vector."""
        ),
        code(
            """vectors = np.asarray(encode_texts([user_e5_text, article_e5_text]))
user_vector, article_vector = vectors

display({
    'combined_tensor_shape': vectors.shape,
    'user_vector_shape': user_vector.shape,
    'article_vector_shape': article_vector.shape,
    'user_vector_norm': round(float(np.linalg.norm(user_vector)), 5),
    'article_vector_norm': round(float(np.linalg.norm(article_vector)), 5),
})
print('FIRST 20 USER-VECTOR VALUES')
display(np.round(user_vector[:20], 5))
print('FIRST 20 ARTICLE-VECTOR VALUES')
display(np.round(article_vector[:20], 5))"""
        ),
        markdown(
            """## 5. Calculate semantic similarity

Because both vectors are normalized, their dot product is also cosine similarity. A
higher value means the complete user profile and article are closer in meaning."""
        ),
        code(
            """semantic_similarity = float(np.dot(user_vector, article_vector))

print('DOT PRODUCT / COSINE SIMILARITY:', round(semantic_similarity, 4))
print('DISPLAYED AS:', round(semantic_similarity * 100), '% semantic similarity')"""
        ),
        markdown(
            """## 6. Keep exact and semantic evidence separate

Exact evidence is deterministic canonical-value overlap. Semantic evidence comes from
E5 and can connect related wording that is not already an exact match."""
        ),
        code(
            """exact_matches = find_exact_matches(user, article)
semantic_matches = find_embedding_signals(user, article)

print('EXACT EVIDENCE')
display(exact_matches)
print('SEMANTIC EVIDENCE NOT ALREADY COUNTED AS EXACT')
display(semantic_matches)"""
        ),
        markdown(
            """## 7. Calculate the hybrid recommendation score

The current prototype uses a transparent hand-written formula:

```text
(E5 semantic score x 75%) + (exact metadata coverage x 25%)
```

The weights are prototype settings. They were not learned by Qwen or E5."""
        ),
        code(
            """selected_result = score_article_for_user(user, article)
manual_score = round(
    selected_result['embedding_score'] * 0.75
    + selected_result['metadata_score'] * 0.25
)

print(
    f\"({selected_result['embedding_score']} x 0.75) + \"
    f\"({selected_result['metadata_score']} x 0.25) = {manual_score}%\"
)
display({
    'E5_embedding_score': selected_result['embedding_score'],
    'exact_metadata_coverage': selected_result['metadata_score'],
    'final_score': selected_result['score'],
    'tier': selected_result['match_tier'],
    'visible_explanations': selected_result['reasons'],
})"""
        ),
        markdown(
            """## 8. Repeat the comparison for every article and rank them

Direct required-filter matches sort before broader related results. The table keeps the
two component scores visible so the final number is explainable."""
        ),
        code(
            """ranked = rank_articles_for_user(user, articles)
ranking_preview = [
    {
        'rank': rank,
        'article_id': result['article']['article_id'],
        'title': result['article']['title'],
        'tier': result['match_tier'],
        'E5_score': result['embedding_score'],
        'exact_score': result['metadata_score'],
        'final_score': result['score'],
    }
    for rank, result in enumerate(ranked[:5], start=1)
]
display(ranking_preview)"""
        ),
        markdown(
            """## 9. Evaluate the ranking against reviewed expectations

Recall@5 asks whether the articles manually marked relevant appeared in the first five
results. These cases evaluate behavior; they are not the source of all model knowledge."""
        ),
        code(
            """cases = load_evaluation_cases(DATA_DIR)
evaluation = evaluate_ranking_cases(
    users,
    articles,
    cases,
    rank_articles_for_user,
    k=5,
)
display(evaluation)"""
        ),
        markdown(
            """## What this notebook proves

- Qwen + LoRA supplies structured article facts.
- Catalogue enrichment currently resolves known aliases to canonical IDs.
- Multilingual E5 creates live 768-dimensional user and article vectors.
- Exact matching and semantic similarity remain separate visible signals.
- A transparent formula combines them into ranked recommendations.

Current limitations:

- E5 is pretrained and has not yet been fine-tuned on real relevance feedback.
- Entity linking is currently catalogue-based rather than learned.
- The data is a small mock demonstration.
- Production quality requires larger reviewed datasets and realistic evaluation."""
        ),
    ]


def rebuild_recommendation_notebook():
    path = NOTEBOOK_DIR / "tactical_report_recommendation_demo.ipynb"
    old_notebook = nbformat.read(path, as_version=4)
    notebook = nbformat.v4.new_notebook(
        cells=recommendation_cells(),
        metadata=deepcopy(old_notebook.metadata),
    )
    execute_notebook(notebook)
    nbformat.write(notebook, path)


def main():
    enhance_qlora_notebook()
    rebuild_recommendation_notebook()
    print("Enhanced and saved both presentation notebooks.")


if __name__ == "__main__":
    main()
